### ISSUE TITLE
error in line 12

### ISSUE THREAD

**Issue by abdazzamajhari** [ukcodes/Flight-Data-Analysis-SJY182#1]
`
# rename the column titles in the English language
for dl in tab_name:
    data_dict[dl].set_axis(['Time', 'Latitude', 'Longitude', 'Heading', 'Kts', 'km/h', 'Altitude', 'RoC', 'Reporting Facility'], 
                axis = 1, inplace = True)
`

Length mismatch: Expected axis has 1 elements, new values have 9 elements

**Comment by abdazzamajhari** [comment]
so, im adding data before from 9 january 2021 backward to november 2020 and get this error

'https://flightaware.com/live/flight/SJY182/history/20210109/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20210104/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201217/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201215/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201212/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201210/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201205/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201203/0640Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201202/0915Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201201/0915Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201128/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201127/0915Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201125/0915Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201124/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201121/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201114/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201110/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201107/0750Z/WIII/WIOO',
'https://flightaware.com/live/flight/SJY182/history/20201103/0750Z/WIII/WIOO',

**Comment by ukcodes** [comment]
Data are not available for 20201110 and 20201103.  Please check (the last and the third line from the bottom of the list posted above)

https://flightaware.com/live/flight/SJY182/history/20201110/0750Z/WIII/WIOO 

https://flightaware.com/live/flight/SJY182/history/20201103/0750Z/WIII/WIOO

So, please remove the above URLs from the list of the webpages for data extraction. 

Please don't hesitate to share if you encounter further problems.

**Comment by abdazzamajhari** [comment]
ah oke then, im not thorough... thanks
