### ISSUE TITLE
Want to ask

### ISSUE THREAD

**Issue by abdazzamajhari** [ukcodes/Flight-Data-Analysis-SJY182#2]
Sorry, i just want to ask about inclination.. what math formula do you use so that it becomes the basis for the visualization? If the degree - (minus) its a normal data?

**Comment by ukcodes** [comment]
By inclination I mean the angle that the velocity vector makes with the horizontal. 

It is equal to Arctan(Rate of Climb/Ground Speed). The Rate of Climb (RoC) and Ground Speed (km/h) are included in the ADS-B data.

If the 'km/h' reported in the ADS-B data is the total velocity magnitude then inclination = arcsin('RoC'/'km/h').

**Comment by abdazzamajhari** [comment]
Could you explain to me about angle the velocity vector? Or the name of base math algorithm, i want to learn about inclination. Is it similiar like angle of bank?

**Comment by ukcodes** [comment]
As you know, the velocity is a vector. It can be decomposed into components along any two orthogonal directions. Here, the total velocity of the aircraft can be written as a vector sum of its velocity in the horizontal direction (ground speed) and its velocity in the vertical direction (Rate of Climb). The total velocity vector, ground speed, and rate of climb form a right-angle triangle in which the total velocity vector is the hypotenuse, the rate of climb is the perpendicular and the ground speed is the base. Therefore, the angle that the total velocity vector makes with the horizontal is equal to arctan(Rate of climb/ground speed). I am referring to this angle as the inclination (or the angle of attack).

**Comment by abdazzamajhari** [comment]
cool! i love your explanation. thanks
